[package]
name = "yatch-app"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "5.0.1"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-functions = { path = "../../emscripten-functions/emscripten-functions/", version = "0.2.5" }
