[package]
name = "yatch-server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
futures-util = "0.3.31"
log = "0.4.26"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
